import { addExtraWords } from "./extra-words";
import { enrichEditorial } from "./editorial";
import { enrichMangystau } from "./mangystau";
import { enrichPavlodar } from "./pavlodar";
import { enrichAtyrau } from "./atyrau";
import type { Region, Card } from "./types";
import { vocabularyFor } from "./vocabulary";
// Explicit current administrative IDs, source SVG label positions (same camera coordinates).
type Seed = [
  string,
  string,
  string,
  string,
  string,
  number,
  number,
  Region["theme"],
  string,
  string,
  string,
  string,
  string,
];
const seeds: Seed[] = [
  [
    "abay",
    "Абай облысы",
    "Абайская область",
    "Abai Region",
    "Семей",
    793.2,
    270,
    "steppe",
    "KZ10",
    "abay-region",
    "Ертіс бойындағы әдеби мұра",
    "Жидебай|Абайдың Семейдегі мұражайы|Қоңыр әулие үңгірі|Семей аспалы көпірі",
    "кітап,ақын,өзен,мұра,дала,мұражай,көпір,қала,құс,домбыра",
  ],
  [
    "akmola",
    "Ақмола облысы",
    "Акмолинская область",
    "Akmola Region",
    "Көкшетау",
    566.8,
    157.8,
    "steppe",
    "KZ11",
    "akmola-province",
    "Көлдер, қарағайлар және құстар мекені",
    "Бурабай|Қорғалжын қорығы|Бөлектау|АЛЖИР мұражайы",
    "көл,қарағай,қорық,қоқиқаз,орман,тау,құс,дала,мұражай,бидай",
  ],
  [
    "aktobe",
    "Ақтөбе облысы",
    "Актюбинская область",
    "Aktobe Region",
    "Ақтөбе",
    302.8,
    275.2,
    "desert",
    "KZ15",
    "aktobe-province",
    "Мұғалжар мен кең даланың тоғысы",
    "Мұғалжар|Ырғыз-Торғай резерваты|Қобыланды батыр кесенесі|Ақтөбе өлкетану мұражайы",
    "дала,тау,қорық,жануар,кен,темір,зауыт,егін,қала,кесене",
  ],
  [
    "almaty-region",
    "Алматы облысы",
    "Алматинская область",
    "Almaty Region",
    "Қонаев",
    707.7,
    419.3,
    "mountain",
    "KZ19",
    "almaty-province",
    "Шатқалдар мен биік таудағы көлдер",
    "Шарын шатқалы|Көлсай көлдері|Қайыңды көлі|Түрген сарқырамалары",
    "тау,көл,сарқырама,мұздық,сай,бұлақ,жартас,орман,жайлау,қорық",
  ],
  [
    "atyrau",
    "Атырау облысы",
    "Атырауская область",
    "Atyrau Region",
    "Атырау",
    206.7,
    306.3,
    "sea",
    "KZ23",
    "atyrau-province",
    "Жайық Каспийге құятын өлке",
    "Индер көлі|Ақкерегешін|Қиғаш өзені|Сарайшық",
    "өзен,теңіз,жағалау,порт,кеме,мұнай,көл,құс,мұра,көпір",
  ],
  [
    "west-kazakhstan",
    "Батыс Қазақстан облысы",
    "Западно-Казахстанская область",
    "West Kazakhstan Region",
    "Орал",
    138.5,
    225.3,
    "steppe",
    "KZ27",
    "west-kazakhstan-province",
    "Жайық жағасы мен Бөкей ордасының мұрасы",
    "Бөкей ордасы мұражайы|Жәңгір хан мұражайы|Аққұм|Орал өлкетану мұражайы",
    "өзен,дала,мұражай,мұра,қала,домбыра,күй,орман,егін,сауда",
  ],
  [
    "zhambyl",
    "Жамбыл облысы",
    "Жамбылская область",
    "Zhambyl Region",
    "Тараз",
    617.8,
    409.5,
    "mountain",
    "KZ31",
    "jambyl-province",
    "Көне Тараздан қызғалдақты тау бөктеріне",
    "Айша бибі кесенесі|Бабаджа қатын кесенесі|Ақыртас|Қарахан кесенесі",
    "кесене,күмбез,қызғалдақ,тау,жібек,сауда,мұра,қала,қамал,бұлақ",
  ],
  [
    "zhetysu",
    "Жетісу облысы",
    "Область Жетісу",
    "Zhetysu Region",
    "Талдықорған",
    761.3,
    369.8,
    "mountain",
    "KZ33",
    "zhetysu-region",
    "Жоңғар Алатауы мен Іле аңғары",
    "Алтын-Емел|Әншіқұм|Жаркент мешіті|Бұрқанбұлақ",
    "тау,сарқырама,құм,өзен,қорық,жайлау,алма,құс,жартас,бұлақ",
  ],
  [
    "karaganda",
    "Қарағанды облысы",
    "Карагандинская область",
    "Karaganda Region",
    "Қарағанды",
    655.4,
    281.3,
    "steppe",
    "KZ35",
    "karagandy-province",
    "Сарыарқаның таулары мен кеншілер еңбегі",
    "Қарқаралы|Кент таулары|Долинка мұражайы|Балқаш көлі",
    "көмір,кенші,зауыт,көл,тау,қарағай,мыс,теміржол,мұражай,дала",
  ],
  [
    "kostanay",
    "Қостанай облысы",
    "Костанайская область",
    "Kostanay Region",
    "Қостанай",
    426.6,
    150.4,
    "steppe",
    "KZ39",
    "kostanay-province",
    "Наурызым ормандары мен Торғай даласы",
    "Наурызым қорығы|Екідің|Торғай геоглифтері|Аманқарағай",
    "бидай,егін,дала,қарағай,қайың,қорық,құс,темір,кен,мұражай",
  ],
  [
    "kyzylorda",
    "Қызылорда облысы",
    "Кызылординская область",
    "Kyzylorda Region",
    "Қызылорда",
    428.1,
    381.7,
    "desert",
    "KZ43",
    "kyzylorda-province",
    "Сырдария, Арал және ғарышқа жол",
    "Байқоңыр ғарыш айлағы|Солтүстік Арал|Қорқыт ата кешені|Қамбаш көлі",
    "күріш,өзен,қобыз,көл,шөл,түйе,мұра,құм,кеме,жағалау",
  ],
  [
    "mangystau",
    "Маңғыстау облысы",
    "Мангистауская область",
    "Mangystau Region",
    "Ақтау",
    212.6,
    417.5,
    "sea",
    "KZ47",
    "mangystau-province",
    "Каспийден Үстірттің ақ жартастарына",
    "Бозжыра|Шерқала|Айрақты|Торыш|Үстірт қорығы|Бекет ата|Шақпақ ата|Отпан тау",
    "түбек,жағалау,қорық,теңіз,кеме,порт,итбалық,мұнай,жартас,үстірт",
  ],
  [
    "pavlodar",
    "Павлодар облысы",
    "Павлодарская область",
    "Pavlodar Region",
    "Павлодар",
    702.5,
    146.2,
    "steppe",
    "KZ55",
    "pavlodar-province",
    "Баянауыл көлдері мен Ертіс жағасы",
    "Баянауыл|Жасыбай көлі|Екібастұз көмір алабы|Сабындыкөл",
    "көмір,көл,өзен,қарағай,тау,зауыт,пойыз,кенші,дала,жартас",
  ],
  [
    "north-kazakhstan",
    "Солтүстік Қазақстан облысы",
    "Северо-Казахстанская область",
    "North Kazakhstan Region",
    "Петропавл",
    513.2,
    93.6,
    "steppe",
    "KZ59",
    "north-kazakhstan-province",
    "Қайыңды орман, көлдер және Ботай ізі",
    "Имантау көлі|Шалқар көлі|Абылай хан резиденциясы|Ботай қонысы",
    "қайың,орман,көл,егін,бидай,дала,мұра,мұражай,құс,жайлау",
  ],
  [
    "turkistan",
    "Түркістан облысы",
    "Туркестанская область",
    "Turkistan Region",
    "Түркістан",
    530.7,
    475.7,
    "desert",
    "KZ61",
    "turkistan-province",
    "Жібек жолының қалалары мен көк күмбездер",
    "Қожа Ахмет Ясауи кесенесі|Отырар|Сауран|Ақмешіт үңгірі",
    "кесене,күмбез,мұра,сауда,жібек,қамал,мақта,қызғалдақ,қорық,қала",
  ],
  [
    "ulytau",
    "Ұлытау облысы",
    "Область Ұлытау",
    "Ulytau Region",
    "Жезқазған",
    522.7,
    306.1,
    "steppe",
    "KZ62",
    "ulytau-region",
    "Ұлы даланың тарихи жүрегі",
    "Жошы хан кесенесі|Алаша хан кесенесі|Домбауыл|Теректі әулие",
    "мыс,кен,кесене,мұра,жартас,тау,дала,кенші,домбыра,жайлау",
  ],
  [
    "east-kazakhstan",
    "Шығыс Қазақстан облысы",
    "Восточно-Казахстанская область",
    "East Kazakhstan Region",
    "Өскемен",
    889,
    258.1,
    "mountain",
    "KZ63",
    "east-kazakhstan-province",
    "Алтай ормандары мен мұздықтары",
    "Қатонқарағай|Марқакөл|Батыс Алтай қорығы|Қиын-Керіш",
    "тау,мұздық,орман,көл,қорық,сарқырама,өзен,кен,жануар,қарағай",
  ],
  [
    "astana",
    "Астана қаласы",
    "Город Астана",
    "Astana",
    "",
    600.4,
    185,
    "city",
    "KZ71",
    "astana",
    "Есіл бойындағы елорда",
    "Бәйтерек|Нұр Әлем|Бейбітшілік және келісім сарайы|Сәкен Сейфуллин мұражайы",
    "елорда,өзен,көпір,ғимарат,сәулет,саябақ,мұражай,қала,пойыз,кітап",
  ],
  [
    "almaty-city",
    "Алматы қаласы",
    "Город Алматы",
    "Almaty City",
    "",
    722.9,
    445,
    "city",
    "KZ75",
    "almaty",
    "Алатау баурайындағы жасыл қала",
    "Медеу|Шымбұлақ|Көктөбе|Жасыл базар",
    "алма,тау,саябақ,қала,сәулет,мұражай,ғимарат,сауда,қарағай,көпір",
  ],
  [
    "shymkent",
    "Шымкент қаласы",
    "Город Шымкент",
    "Shymkent",
    "",
    559.2,
    472.7,
    "city",
    "KZ79",
    "shymkent",
    "Оңтүстіктің қонақжай шаһары",
    "Шымкент цитаделі|Дендросаябақ|Қошқар ата өзені|Тәуелсіздік саябағы",
    "қала,саябақ,өзен,сауда,мұра,ғимарат,қамал,сәулет,қызғалдақ,бұлақ",
  ],
];
const card = (
  id: string,
  title: string,
  text: string,
  icon = "mountain",
): Card => ({ id, title, text, icon });
export const regions: Region[] = seeds.map(
  ([
    id,
    nameKk,
    nameRu,
    nameEn,
    capital,
    x,
    y,
    theme,
    mapFeatureId,
    sourceSlug,
    shortDescription,
    places,
    keys,
  ]) => {
    const vocabulary = vocabularyFor(keys.split(","));
    const landmarks = places
      .split("|")
      .map((title, i) =>
        card(
          `${id}-place-${i}`,
          title,
          `${nameKk}: ${title}. Өңірдің осы нысанын атауы арқылы танып үйрен.`,
          /кесене|мұражай|сарай|мешіт|цитадел|мұра|кешен|резиденц/.test(title)
            ? "monument"
            : /көл|Арал|өзен/.test(title)
              ? "wave"
              : "mountain",
        ),
      );
    const sources = [
      {
        title: "Қазақстан туризмі · өңір туралы",
        url: `https://kazakhstan.travel/en/regions/${sourceSlug}`,
      },
      {
        title: "Ұлттық статистика бюросы · әкімшілік бөлініс",
        url: "https://stat.gov.kz/en/industries/socialtatistics/demography/publications/318188/",
      },
    ];
    const nature = [
      card(
        `${id}-nature`,
        shortDescription,
        `${nameKk}${capital ? ` орталығы — ${capital}.` : " — республикалық маңызы бар қала."} ${shortDescription}.`,
        theme === "sea" ? "wave" : theme === "city" ? "city" : "mountain",
      ),
    ];
    const quiz = [
      {
        prompt: capital
          ? "Облыс орталығын тап."
          : "Бұл аумақтың мәртебесі қандай?",
        options: capital
          ? [capital, "Ақтау", "Тараз", "Көкшетау"].filter(
              (v, i, a) => a.indexOf(v) === i,
            )
          : ["Республикалық маңызы бар қала", "Облыс", "Аудан"],
        answer: capital || "Республикалық маңызы бар қала",
        explanation: capital
          ? `${nameKk} орталығы — ${capital}.`
          : `${nameKk} — облыстан бөлек әкімшілік аумақ.`,
      },
      {
        prompt: `«${vocabulary[0].kk}» сөзінің орысша аудармасы?`,
        options: [vocabulary[1].ru, vocabulary[0].ru, vocabulary[2].ru],
        answer: vocabulary[0].ru,
        explanation: vocabulary[0].definition,
      },
      {
        prompt: "Өңірдің көрікті жерін таңда.",
        options: [
          landmarks[0].title,
          regionsPlaceholder(id),
          "Париждегі Эйфель мұнарасы",
        ],
        answer: landmarks[0].title,
        explanation: `${landmarks[0].title} — ${nameKk} аумағындағы нысан.`,
      },
      {
        prompt: `«${vocabulary[2].kk}» сөзінің ағылшынша аудармасы?`,
        options: [vocabulary[1].en, vocabulary[3].en, vocabulary[2].en],
        answer: vocabulary[2].en,
        explanation: vocabulary[2].definition,
      },
      {
        prompt: "Табиғи және тарихи нысандарда не істеу керек?",
        options: ["Қоқыс қалдыру", "Мұраны сақтау", "Жартасты бояу"],
        answer: "Мұраны сақтау",
        explanation: "Тарихи мұра мен табиғатты келесі ұрпаққа сақтау керек.",
      },
    ];
    return {
      id,
      slug: id,
      nameKk,
      nameRu,
      nameEn,
      type: capital ? "region" : "city",
      capital: capital || undefined,
      coordinates: { x, y },
      mapFeatureId,
      theme,
      shortDescription,
      nature,
      landmarks,
      animals: [],
      plants: [],
      history: [],
      culture: [],
      foods: [],
      famousPeople: [],
      resources: [],
      industries: [],
      agriculture: [],
      importance: [
        card(
          `${id}-importance`,
          "Таны, үйрен, сақта",
          shortDescription,
          "book",
        ),
      ],
      interestingFacts: [
        capital ? `Орталығы — ${capital}.` : "Республикалық маңызы бар қала.",
        ...landmarks
          .slice(0, 4)
          .map((l) => `${l.title} осы аумақта орналасқан.`),
      ],
      vocabulary,
      games: {
        quiz,
        matching: vocabulary.slice(0, 3).map((w) => w.id),
        sentence: vocabulary[0].example.split(" "),
      },
      mapObjects: landmarks.slice(0, 3).map((l, i) => ({
        ...l,
        type: "history" as const,
        wordId: vocabulary[i].id,
        coordinates: { x: x + (i - 1) * 18, y: y + 20 },
        minZoom: 2,
      })),
      ambientAnimations:
        theme === "sea"
          ? ["wave", "ship", "bird", "pump"]
          : theme === "city"
            ? ["lights", "train"]
            : theme === "mountain"
              ? ["cloud", "tree", "bird"]
              : ["grass", "cloud", "train"],
      stamp: landmarks[0].icon,
      sources,
      contentStatus: "partial",
      missingContent: [
        "Жануарлардың өңірлік мекені мен қорғау мәртебесі",
        "Өсімдіктер, мәдениет, тағам және тұлғалар туралы толық тексерілген карточкалар",
        "Өндіріс байланыстары мен нысандардың нақты сипаттамалары",
      ],
    };
  },
);
function regionsPlaceholder(id: string) {
  return id === "mangystau" ? "Бәйтерек" : "Бозжыра";
}
export const regionById = (id: string) => regions.find((r) => r.id === id);

enrichMangystau(regions.find((r) => r.id === "mangystau")!);

enrichEditorial(regions);

addExtraWords(regions);
enrichPavlodar(regions.find((r) => r.id === "pavlodar")!);
enrichAtyrau(regions.find((r) => r.id === "atyrau")!);
