import { writeFileSync } from "node:fs";
import {
  achievements,
  books,
  courses,
  lessons,
  quests,
} from "../lib/learning/content";
const sql = (value: unknown) =>
  value === null
    ? "null"
    : `'${(typeof value === "string" ? value : JSON.stringify(value)).replaceAll("'", "''")}'`;
const statements = [
  "-- Generated by npm run seed:learning. Edit lib/learning/content.ts, then regenerate.",
  "begin;",
];
function insert(table: string, columns: string[], values: unknown[]) {
  statements.push(
    `insert into public.${table} (${columns.join(",")}) values (${values.map(sql).join(",")}) on conflict do nothing;`,
  );
}
for (const b of books) {
  insert(
    "qd_books",
    ["id", "title", "author", "content"],
    [b.id, b.title, b.author, b],
  );
  for (const ch of b.chapters)
    insert(
      "qd_book_chapters",
      ["id", "book_id", "title", "summary"],
      [ch.id, b.id, ch.title, ch.summary],
    );
}
for (const c of courses) {
  insert(
    "qd_courses",
    ["id", "title", "description"],
    [c.id, c.title, c.description],
  );
  c.sections.forEach((s, i) => {
    insert(
      "qd_sections",
      ["id", "course_id", "position", "title"],
      [s.id, c.id, i, s.title],
    );
    s.lessonIds.forEach((id, j) => {
      const l = lessons.find((x) => x.id === id)!;
      insert(
        "qd_lessons",
        ["id", "section_id", "book_id", "position", "title", "kind"],
        [id, s.id, l.bookId ?? null, j, l.title, l.kind],
      );
      l.exercises.forEach((e, k) => {
        insert(
          "qd_exercises",
          ["id", "lesson_id", "position", "content"],
          [e.id, id, k, e],
        );
        e.options?.forEach((o) =>
          insert(
            "qd_exercise_options",
            ["exercise_id", "id", "content"],
            [e.id, o.id, o],
          ),
        );
        if (l.bookId)
          insert(
            "qd_book_questions",
            ["book_id", "exercise_id"],
            [l.bookId, e.id],
          );
      });
    });
  });
}
for (const b of books)
  insert("qd_book_quizzes", ["book_id", "lesson_id"], [b.id, b.quiz.lessonId]);
for (const a of achievements)
  insert("qd_achievements", ["id", "content"], [a.id, a]);
for (const q of quests) insert("qd_daily_quests", ["id", "content"], [q.id, q]);
statements.push("commit;");
writeFileSync(
  "supabase/migrations/202609070002_learning_content.sql",
  statements.join("\n") + "\n",
);
console.log(
  `Seed generated: ${courses.length} courses, ${lessons.length} lessons, ${lessons.reduce((a, l) => a + l.exercises.length, 0)} exercises.`,
);
